// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import BarChartOutlined from '/Users/suplay/Desktop/myapp-main1/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import CrownOutlined from '/Users/suplay/Desktop/myapp-main1/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { BarChartOutlined, CrownOutlined };
