// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/user","layout":false,"id":"1"},"2":{"path":"/user","parentId":"1","id":"2"},"3":{"name":"login","path":"/user/login","file":"@/pages/user/Login/index.tsx","parentId":"2","id":"3"},"4":{"file":"@/pages/404.tsx","parentId":"1","id":"4"},"5":{"path":"/","redirect":"/accountcenter/rolemanagement","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/TableList","name":"TAB","icon":"BarChartOutlined","access":"0","file":"@/pages/TableList/index.tsx","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/accountcenter","name":"账号中心","access":"0","icon":"crown","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/accountcenter/management","name":"账号管理","access":"1","icon":"BarChartOutlined","file":"@/pages/AccountCenter/Management/index.jsx","parentId":"7","id":"8"},"9":{"path":"/accountcenter/rolemanagement","name":"角色管理","icon":"BarChartOutlined","access":"2","file":"@/pages/AccountCenter/RoleManagement/index.jsx","parentId":"7","id":"9"},"10":{"path":"/accountcenter/personalcenter","name":"个人中心","icon":"BarChartOutlined","access":"3","file":"@/pages/AccountCenter/PersonalCenter/index.jsx","parentId":"7","id":"10"},"11":{"file":"@/pages/404.tsx","parentId":"ant-design-pro-layout","id":"11"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi-production/plugin-layout/Layout.tsx","isLayout":true}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import( './EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__user__Login__index" */'@/pages/user/Login/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'5': React.lazy(() => import( './EmptyRoute')),
'6': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'7': React.lazy(() => import( './EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__AccountCenter__Management__index" */'@/pages/AccountCenter/Management/index.jsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__AccountCenter__RoleManagement__index" */'@/pages/AccountCenter/RoleManagement/index.jsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__AccountCenter__PersonalCenter__index" */'@/pages/AccountCenter/PersonalCenter/index.jsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'@/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
