// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  proxy, useSnapshot, snapshot, subscribe,
  proxyWithComputed,
  proxyWithHistory,
  proxyWithDevtools,
  proxyMap,
  proxySet,
} from '/Users/suplay/Desktop/myapp-main1/node_modules/@umijs/valtio';
