// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/suplay/Desktop/myapp-main1/src/pages/AccountCenter/Management/model';
import model_2 from '/Users/suplay/Desktop/myapp-main1/src/pages/AccountCenter/PersonalCenter/model';
import model_3 from '/Users/suplay/Desktop/myapp-main1/src/pages/AccountCenter/RoleManagement/model';

export const models = {
model_1: { namespace: 'AccountCenter.Management.model', model: model_1 },
model_2: { namespace: 'AccountCenter.PersonalCenter.model', model: model_2 },
model_3: { namespace: 'AccountCenter.RoleManagement.model', model: model_3 },
} as const
