// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, Helmet, useAppData, useClientLoaderData, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/suplay/Desktop/myapp-main1/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/suplay/Desktop/myapp-main1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/suplay/Desktop/myapp-main1/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-access';
export { connect, useDispatch, useStore, useSelector, getDvaApp } from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-dva';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-locale';
export { Provider, useModel } from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-request';
export { proxy, useSnapshot, snapshot, subscribe, proxyWithComputed, proxyWithHistory, proxyWithDevtools, proxyMap, proxySet } from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-valtio';
// plugins types.d.ts
export * from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-dva/types.d';
export * from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-layout/types.d';
export * from '/Users/suplay/Desktop/myapp-main1/src/.umi/plugin-request/types.d';
export { defineApp } from './core/defineApp'
export type {  RuntimeConfig } from './core/defineApp'
